import { Http } from '@angular/http';
import 'ScrollMagic';
export declare class OsbPocketPoke {
    http: Http;
    isLoading: boolean;
    navHidden: boolean;
    pokemonApiBase: string;
    caughtPokemon: any[];
    pokemonList: any[];
    pokemonViewList: any[];
    pokemon: any[];
    evolutionChains: any[];
    evolutionViewList: any[];
    evolutions: any[];
    contests: any[];
    berries: any[];
    berriesData: any[];
    berryCount: number;
    locations: any[];
    locationsCount: number;
    locationData: any[];
    locationCount: number;
    sectionDisplay: string;
    pokeListCount: number;
    pageLength: number;
    pokePageCount: number;
    locationsPageCount: number;
    evolutionsPageCount: number;
    berriesPageCount: number;
    pokeCallbackCount: number;
    locationCallbackCount: number;
    evolutionsCallbackCount: number;
    berriesCallbackCount: number;
    pokemonScene: any;
    locationsScene: any;
    constructor(http: Http);
    startScrollMagic(): void;
    startLocationScrollMagic(): void;
    destroyScrollMagic(): void;
    capturePokemon(pokemon: any): void;
    getBerry(berry: any): void;
    setBerry(berry: any): void;
    getBerries(): void;
    setBerries(berries: any): void;
    getEvolution(evolution: any): void;
    setEvolution(evolution: any): void;
    getEvolutionChain(): void;
    setEvolutionChain(evolutions: any): void;
    getLocation(location: any): boolean;
    setLocation(location: any): void;
    getLocations(newList: any): boolean;
    setLocations(locations: any): void;
    getMorePokemon(): void;
    setMorePokemon(pokemonList: any): void;
    updatePokemon(pokemon: any): void;
    getPokemon(pokemon: any, newList: any): boolean;
    setPokemon(pokemon: any, newList: any): void;
    getPokeList(): void;
    setPokeList(data: any): boolean;
}
