import { Http } from '@angular/http';
import 'ScrollMagic';
export declare class OsbPocketPoke {
    http: Http;
    isLoading: boolean;
    navHidden: boolean;
    pokemonApiBase: string;
    caughtPokemon: any[];
    pokemonList: any[];
    pokemon: any[];
    locationData: any[];
    locations: any[];
    evolutionChains: any[];
    evolutions: any[];
    berriesData: any[];
    berries: any[];
    sectionDisplay: string;
    pageLength: number;
    pokePageCount: number;
    locationsPageCount: number;
    evolutionsPageCount: number;
    berriesPageCount: number;
    pokemonScene: any;
    constructor(http: Http);
    startScrollMagic(section: any): void;
    destroyScrollMagic(): void;
    capturePokemon(pokemon: any): void;
    getSectionData(section: any, item: any): void;
    setSectionData(section: any, data: any): void;
    getSectionList(section: any, page: any): boolean;
    setSectionList(section: any, data: any): boolean;
}
